создать классы Film, User, FilmController, UserController, тесты
AlbinaKuznetsova/java-filmorate pull request #5
Opened 2024-02-09 11:33 UTC by AlbinaKuznetsova

2024-02-09 15:10 UTC, andrew-larkin requested changes
Привет! Отличный старт! Архитектурно все выполнено корректно, остается внести небольшие корректировки по коду и работа будет принята.

2024-02-09 15:10 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isBlank()) {
эти проверки лучше вынести в отдельный приватный метод, чтобы они не повторялись от метода к методу

2024-02-09 15:10 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail().isBlank() || !user.getEmail().contains("@")) {
аналогично FilmController

2024-02-09 15:10 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/ValidationException.java
> +public class ValidationException extends Exception {
тут лучше указать RuntimeException, чтобы наследование происходило напрямую от непроверяемых ошибок

2024-02-10 17:05 UTC, AlbinaKuznetsova commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isBlank()) {
Исправлено

2024-02-10 17:05 UTC, AlbinaKuznetsova commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getEmail().isBlank() || !user.getEmail().contains("@")) {
Исправлено

2024-02-10 17:05 UTC, AlbinaKuznetsova commented on src/main/java/ru/yandex/practicum/filmorate/model/ValidationException.java
> +public class ValidationException extends Exception {
Исправлено

2024-02-20 07:17 UTC, merged